# Publishing settings

title: Principles of neurosurgical science
author: Conor Keogh
# logo: get logo?

execute:
    execute_notebooks: force
    
latex:
    latex_documents:
        targetname: principles.tex
        
# Repo information
repository:
    url: github.com/conorkeogh/mrcs_principles
    path_to_book: content
    branch: main

# GitHub buttons
html:
    use_issues_button: true
    use_repository_button: true